### ISSUE TITLE
public ip configuration

### ISSUE THREAD

**Issue by aggarwalaman1191** [andrewCluey/terraform-azurerm-windows-vm#1]
Hi Andrew,

Is it possible to add dynamic block to provide public ip in the ip_configuration?

**Comment by andrewCluey** [comment]
Sorry. Not had chance to review these issues much over the past year or so.

Changes to the network config are planned for a future release, not sure if I'll add the option to assign a Pub IP directly to the VM though. It's not great practice and typically better to use a reverse proxy or Load Balancer for incoming pub' requests (although I appreciate there may be times when assigning a Public IP directly to a Windows VM may be justified).
