### ISSUE TITLE
The example VM name does not comply to the variable limits.

### ISSUE THREAD

**Issue by BertusV** [andrewCluey/terraform-azurerm-windows-vm#2]
The example fails because the vm name in the example does not comply.  It does not allow for "-" to be part of the vm name.

**Comment by andrewCluey** [comment]
Is this an error with the reader or the code itself?

Please submit a PR with proposed changes.

thanks

**Comment by BertusV** [comment]
Hi Andrew,

I believe it's the conditional checks on the VM name not allowing for the dashes in the name.  I'm new to Terraform so I'm not confident is suggesting a fix.

Regards,
Bertus

**Comment by andrewCluey** [comment]
No problem. I’m working on updating the module anyway so will incorporate the fix. New version removes some of the duplication for custom/standard images so it’s better from a `DRY` perspective anyway (hopefully easier to read).

Also, the README file was created from a very early draft version (before I added the REGEX validation for the input). So there are really two errors, an old README, and incorrect REGEX validation. New version (v3) should be released soon.

Thanks

From: Bertus Viljoen ***@***.***>
Date: Friday, 1 July 2022 at 11:10
To: andrewCluey/terraform-azurerm-windows-vm ***@***.***>
Cc: andrew clure ***@***.***>, Comment ***@***.***>
Subject: Re: [andrewCluey/terraform-azurerm-windows-vm] The example VM name does not comply to the variable limits. (Issue #2)
Hi Andrew,

I believe it's the conditional checks on the VM name not allowing for the dashes in the name. I'm new to Terraform so I'm not confident is suggesting a fix.

Regards,
Bertus

**Comment by BertusV** [comment]
Good luck, let me know when you've updated it and I can try again.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
